const plugin = require("tailwindcss/plugin");

module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        breen: {
          blue: "#4F73D1",
          b1: "#444444",
          blueFade: "#F8F9FA",
          lightBlue: "#577CDD",
          transparentBlue: "#CDDFF8",
          gray: "#FAFAFA",
          gray2: "#858B93",
          gray3: "#8D8F92",
          gray4: "#B1B1B1",
          gray5: "#5D687B",
          gray6: "#E2E8F0",
          gray7: "#9EA7B7",
          gray8: "#46556F",
          gray9: "#ECEFF7",
          gray10: "#7A7A7A",
          gray11: "#313131",
          black: "#2D3748",
          lightGray: "#74788D",
          paleBlue: "#E4ECFF",
          offWhite: "#F3F7FF",
          green: "#0ABB87",
          lightRed: "#FDE5EF",
          red: "#FD397A",
          buttonBlue: "#EBF0FF",
        },
      },
      width: {
        "[550px]": "34.375rem",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    plugin(function ({ addUtilities }) {
      const newUtilities = {
        ".text-h1": {
          fontSize: "31px",
          fontStyle: "normal",
          fontWeight: 700,
          lineHeight: "46px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".text-h2": {
          fontSize: "22px",
          fontStyle: "normal",
          fontWeight: 700,
          lineHeight: "33px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".form-label": {
          fontSize: "13px",
          fontStyle: "normal",
          fontWeight: 500,
          lineHeight: "18px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".btn-text": {
          fontSize: "10px",
          fontStyle: "normal",
          fontWeight: 700,
          lineHeight: "15px",
          letterSpacing: "0em",
          textAlign: "center",
        },
        ".btn-text2": {
          fontSize: "13px",
          fontStyle: "normal",
          fontWeight: 500,
          lineHeight: "20px",
          letterSpacing: "0em",
          textAlign: "center",
        },
        ".text-b1": {
          fontSize: "13px",
          fontStyle: "normal",
          fontWeight: 500,
          lineHeight: "18px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".text-b2": {
          fontSize: "13px",
          fontStyle: "normal",
          fontWeight: 400,
          lineHeight: "20px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".text-search": {
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: 400,
          lineHeight: "21px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".text-nav": {
          fontSize: "13px",
          fontStyle: "normal",
          fontWeight: 500,
          lineHeight: "20px",
          letterSpacing: "0em",
          textAlign: "right",
        },
        ".text-side": {
          fontSize: "15px",
          fontStyle: "normal",
          fontWeight: 500,
          lineHeight: "23px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".text-ttitle": {
          fontSize: "18px",
          fontStyle: "normal",
          fontWeight: 500,
          lineHeight: "25px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".text-theader": {
          fontSize: "13px",
          fontStyle: "normal",
          fontWeight: 700,
          lineHeight: "20px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".text-tdata": {
          fontSize: "13px",
          fontStyle: "normal",
          fontWeight: 400,
          lineHeight: "18px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".msg-header": {
          fontSize: "18px",
          fontStyle: "normal",
          fontWeight: 700,
          lineHeight: "25px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".msg-title": {
          fontSize: "13px",
          fontStyle: "normal",
          fontWeight: 600,
          lineHeight: "18px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".msg-text": {
          fontSize: "13px",
          fontStyle: "normal",
          fontWeight: 400,
          lineHeight: "18px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".modal-title": {
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: 500,
          lineHeight: "24px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".upload-title": {
            fontSize: "18px",
            fontStyle: "normal",
            fontWeight: 500,
            lineHeight: "27px",
            letterSpacing: "0em",
            textAlign: "center",
          },
        ".upload-text": {
            fontSize: "13px",
            fontStyle: "normal",
            fontWeight: 400,
            lineHeight: "20px",
            letterSpacing: "-0.02em",
            textAlign: "center",
        }
      };

      return addUtilities(newUtilities, ["responsive"]);
    }),
  ],
};
